name = "coreutils"
version = "9.5"
description = "Basic file, shell and text manipulation utilities"
homepage = "https://www.gnu.org/software/coreutils/"
license = ["GPL-3.0"]
source = "https://ftp.gnu.org/gnu/coreutils/coreutils-9.5.tar.xz"
build_system = "autotools"
depends = ["glibc"]
optional_depends = []
