name = "pipewire"
version = "1.2.0"
description = "A multimedia server for Linux and Wayland"
homepage = "https://pipewire.org/"
license = ["MIT"]
source = "https://gitlab.freedesktop.org/pipewire/pipewire/-/archive/1.2.0/pipewire-1.2.0.tar.gz"
build_system = "meson"
depends = ["glibc"]
optional_depends = ["libX11", "libXrandr", "alsa-lib", "libpulse"]
