name = "zlib"
version = "1.3.1"
description = "A compression library implementing the deflate compression algorithm"
homepage = "https://zlib.net/"
license = ["Zlib"]
source = "https://zlib.net/zlib-1.3.1.tar.gz"
build_system = "cmake"
depends = ["glibc"]
optional_depends = []
