name = "ripgrep"
version = "14.1.0"
description = "A line-oriented search tool that recursively searches the current directory"
homepage = "https://github.com/BurntSushi/ripgrep"
license = ["MIT", "Unlicense"]
source = "https://github.com/BurntSushi/ripgrep/archive/refs/tags/14.1.0.tar.gz"
build_system = "cargo"
depends = ["glibc"]
optional_depends = []
