name = "tealdeer"
version = "1.7.1"
description = "A very fast implementation of tldr in Rust"
homepage = "https://github.com/tealdeer-rs/tealdeer"
license = ["Apache-2.0"]
source = "https://github.com/tealdeer-rs/tealdeer/archive/refs/tags/v1.7.1.tar.gz"
build_system = "cargo"
depends = ["glibc"]
optional_depends = []
